### ISSUE TITLE
Composer `codeigniter-third-party` package

### ISSUE THREAD

**Issue by david-sosa-valdes** [ingeniasoftware/luthier-ci#1]
This is more a feature/request for this project, maybe we can install it with composer like:

```
composer require luthier/driver
```

Or something like that with https://github.com/composer/installers

**Comment by andersonsalas** [comment]
Yes! The project will be available as a composer package as soon as reach the first stable release  :)

**Comment by andersonsalas** [comment]
Luthier is now available with Composer
