### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by robertsanseries** [ingeniasoftware/luthier-ci#10]
1. It is important to put in README.md that in order to generate the files you must grant permission to write to the folders!

2. Use the Wiki to better describe the usage and add the README.md link ... If you do not have the time, I'd be happy to help you document!

Thank you very much for the package!

**Comment by andersonsalas** [comment]
Hi!

We are currently working on the documentation of the project (I did not expected that was so huge) so in a few days it will be finished and published in the repo and the README.md file will be updated according to this suggestion :smiley:

Cheers.

**Comment by andersonsalas** [comment]
The documentation is ready!, checkout the last commits and the readme.md :tada:
