### ISSUE TITLE
Regex param group and function call

### ISSUE THREAD

**Issue by hostekevin** [ingeniasoftware/luthier-ci#15]
Hello,

Is there a solution to use a group route with a regex param and get the right param in the sub function route ?

The code will be more explicit :

```php
// In the routes/web.php
Route::group('{((en|fr)):_locale}', function()
{
    Route::get('{id}', 'page@show');
});

// In the page controller
class Page extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function page($id) {
         echo $id;
         // show 'en' or 'fr' but not the id
    }
}
```

When using this ```'{((en|fr)):_locale}'``` instead of ```{_locale}``` the params in the function is wrong.

Example: i call the route /en/123 and i get 'en'
Without the regex i get '123'

Thanks for your help

**Comment by andersonsalas** [comment]
Hi @Kevkehz

Yes, that's a bug, thanks for report it. It will be fixed in a few days with the next release!  :smile:

**Comment by andersonsalas** [comment]
[Version 0.3.0](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v0.3.0) released

**Comment by hostekevin** [comment]
Thanks a lot :)
