### ISSUE TITLE
Whoops does not work with Luthier-ci

### ISSUE THREAD

**Issue by robertsanseries** [ingeniasoftware/luthier-ci#16]
while adding luthier-ci, the library screams stops working.

https://stackoverflow.com/questions/47190068/codeigniter-3-with-whoops?rq=1

http://www.universidadecodeigniter.com.br/whoops-error-handling-personalizado-no-codeigniter/

**Comment by andersonsalas** [comment]
Hi @robertsanseries, just add another index to the `$hook` array:

```php
# application/config/hooks.php

$hook = Luthier\Hook::getHooks();

$hook['pre_system'][] = function(){
    $whoops = new Whoops\Run;
    $whoops->pushHandler(new Whoops\Handler\PrettyPageHandler());
    $whoops->register();
}; 
```

**Comment by robertsanseries** [comment]
Thanks! :D
