### ISSUE TITLE
PHP 5.6 compatibility

### ISSUE THREAD

**Issue by hostekevin** [ingeniasoftware/luthier-ci#17]
Hello,

I found an error when deploying on a 5.6 php version :

```
Fatal error: Cannot use Luthier\RouteBuilder as Route because the name is already in use in vendor\luthier\luthier\src\Debug.php on line 15
```

Removing this line allow me to use it with php 5.6
```php
use Luthier\RouteBuilder as Route;
```

thanks

**Comment by hostekevin** [comment]
I see that is already solved in github project ?

**Comment by andersonsalas** [comment]
Hi! I confirmed the bug (PHP 5.6/W8.1 x64) but when remove that line I got the following fatal error:

```
Fatal error: Default value for parameters with a class type hint can only be NULL in C:\Apache\htdocs\luthier-ci-tester\application\vendor\symfony\var-dumper\Dumper\CliDumper.php on line 61
```
Let me make a few tests before pushing the changes in the repo, just for being sure :+1:

**Comment by andersonsalas** [comment]
[Versión 1.0.0](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v1.0.0) released

**Comment by hostekevin** [comment]
Thank you :)
