### ISSUE TITLE
Migrate command fail

### ISSUE THREAD

**Issue by abmcr** [ingeniasoftware/luthier-ci#20]
I want to launch 
`php index.php luthier migrate`

for enable simple AUTH, but i get this

`ERROR: Not Found

        The controller/method pair you requested was not found.`

Previous, the 

`php index.php luthier make auth`

work fine

**Comment by andersonsalas** [comment]
Hi @abmcr, thanks for report it. Will be fixed ASAP :+1: 

There is a workaround:

```
php index.php luthier migrate refresh
```

**Comment by abmcr** [comment]
Thank you: i have tried with refresh but

`
andrea@MacBook-Pro-ABERSI:~/projects/ci3$ php index.php luthier migrate refresh

ERROR: An Error Was Encountered

        Migrations has been loaded but is disabled or set up incorrectly.
`

in my routes/cli.php i have this

`Luthier\Cli::maker();
Luthier\Cli::migrations();`

**Comment by andersonsalas** [comment]
You must enable the migrations in your app (`application/config/migration.php` file):

```php
$config['migration_enabled'] = TRUE;  
```

**Comment by abmcr** [comment]
ok thank you

**Comment by andersonsalas** [comment]
[Version 1.0.1](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v1.0.1) released

**Comment by abmcr** [comment]
OK this solve the problem
