### ISSUE TITLE
A Typo in the documentation

### ISSUE THREAD

**Issue by Ihabafia** [ingeniasoftware/luthier-ci#27]
Dear,

I think there is a mistake in the documentation which is:

// Revoking the 'general.read' permission to the current user
$this->simple_auth->grantPermission('general.read');

I think you meant:

// Revoking the 'general.read' permission to the current user
$this->simple_auth->revokePermission('general.read');

Please confirm.

**Comment by andersonsalas** [comment]
Thanks for reporting that typo. It will be fixed in the next update :+1:
