### ISSUE TITLE
PUT or PATCH methods are not going as expected

### ISSUE THREAD

**Issue by Ihabafia** [ingeniasoftware/luthier-ci#32]
How could I direct the form to be a PUT or PATCH request?

I made the route to be PATCH like:

`Route::patch('foo', 'foo@bar')->name(foo.bar);`

but the form keeps going as a POST.

I tried to add a hidden _method input field like Laravel:

`<input type="hidden" name="_method" value="PATCH">`

but it still goes as a POST.

Could you please help.

**Comment by andersonsalas** [comment]
Bug confirmed. It's a typo in the code (`$_SERVER['RQUEST_METHOD']`):

https://github.com/ingeniasoftware/luthier-ci/blob/3161b025de019613e525fd1574c9e53dfa6fa11c/src/Hook.php#L182-L189

**Comment by andersonsalas** [comment]
[Version 1.0.2](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v1.0.2) released :+1:
