### ISSUE TITLE
I bug in catching an Id from the code in the Route::

### ISSUE THREAD

**Issue by Ihabafia** [ingeniasoftware/luthier-ci#33]
I think, there is one more bug somehow.  I will try to explain it:

`Route::post('/{id}', 'AuthCodeController@update')->name('code.update');`

`<a href="<?php route('code.update', [$code->id]) ?>">Edit Code</a>`
or
`<a href="<?php route('code.update', [$code]) ?>">Edit Code</a>`

In both cases, it gives an error:

```
Message: Missing "id" parameter for "code.update" route (View: /Users/xxxxxxxx/Sites/test.mac/application/views/code/edit.blade.php)

Filename: /Users/xxxxxxxx/Sites/test.mac/vendor/luthier/luthier/src/Route.php

Line Number: 399
```
While `$code` class does have a `$code->id` but for some reason it's not catching it.

**Comment by Ihabafia** [comment]
I was able to solve the problem (although I am not sure if that is the best solution but it works), the solution is as follows:

between line 391 - 400 in the Route.php file:

I changed the code from:

```
        foreach($this->params as &$param)
        {
            $name = $param->getName();
            if(!$param->isOptional())
            {
                if(!isset($defaultParams[$name]) && !isset($params[$param->getName()]))
                {
                    throw new \Exception('Missing "' . $name .'" parameter for "' . $this->getName() . '" route');
                }
```

to

```
        foreach($this->params as $index => &$param)
        {
            $name = $param->getName();

            if(!$param->isOptional())
            {
                if(!isset($defaultParams[$name]) && !isset($params[$param->getName()]) && !isset($params[$index]->{$param->getName()}))
                {
                    throw new \Exception('Missing "' . $name .'" parameter for "' . $this->getName() . '" route');
                }

```

After I made that change, it works perfectly.  Please check it out and update.

**Comment by Ihabafia** [comment]
One more in the optional Route Id, that I couldn't solve myself:

`Route::get('/{page?}', 'AuthUserController@index')->name('user.pages');`

`<a href="<?php route('user.pages', ['page' => '2']) ?>">Edit User</a>`

Result is:

`<a href="http://test.mac/user">Edit User</a>`

while it should be:

`<a href="http://test.mac/user/2">Edit User</a>`

But If I changed it to no '?' in the route like:

`Route::get('/{page}', 'AuthUserController@index')->name('user.pages');`

it works just file and the result is: 

`<a href="http://test.mac/user/2">Edit User</a>`

**Comment by andersonsalas** [comment]
Thanks for the bug report. It was a logic mistake. 

In general, all route parameters must be passed as a `name => value`  array to the `route()` function, but if your route defines only one parameter you can pass the value directly, just like Laravel. Here is an example:

```php
Route::get('/{page?}', 'AuthUserController@index')->name('user.pages');

Route::get('/test', function(){
    // Directly:
    echo route('user.pages', 123) . '<br>';
    // As a key => value array
    echo route('user.pages', ['page' => 123]) . '<br>';
})->name('test');
```

**Comment by andersonsalas** [comment]
[Version 1.0.3](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v1.0.3) released.

Let me know if you need more help :)
