### ISSUE TITLE
hmvc at the luthier make command

### ISSUE THREAD

**Issue by wisnubaldas** [ingeniasoftware/luthier-ci#34]
hi..., I use hmvc module, can it be integrated into the luthier make command to create a controller, maybe by adding parameters when creating a controller?

php index.php luthier make [modules] [resource] [name] [type? (sequenatial | date) = date]

**Comment by andersonsalas** [comment]
Sounds good. Let me mark this as a new feature for the next release :)

**Comment by andersonsalas** [comment]
[Version 1.0.4](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v1.0.4) released.

Now its possible to specify the module name when creating controllers, models, libraries and helpers via CLI with the `--module` parameter:

```
// Controllers
php index.php luthier make controller MyController --module:MyModule

// Models
php index.php luthier make model MyModel --module:MyModule

// Libraries
php index.php luthier make library MyLibrary --module:MyModule

// Helpers
php index.php luthier make helper MyHelper --module:MyModule
```

**Comment by wisnubaldas** [comment]
I really like this plugin.. :100:
