### ISSUE TITLE
Parameter order issue of buildUrl in Route Class!

### ISSUE THREAD

**Issue by dmeegh** [ingeniasoftware/luthier-ci#36]
First of all, thank you for using a good framework.

While using the route method, I found a problem with parameter mapping.

A problem has been identified where the mapping order of params passed to buildUrl in Route class and the array_pop sequence inside the foreach syntax does not match.

The parameters were removed from the back while checking from the front.

Am I mistaken?

In addition, all parameters designated as optional will be removed, but there will be a parameter remaining even if no uri is mapped.

`RouteEx::get( 'mng_users/{viewcnt?}/{page?}', 'UsersController@index' )->name( 'admin.users' );`

This is how I assign the uri, and the parameter delivered nothing.

Expected uri should be 'mng_users' only, but 'mng_users/{viewcnt?}'.

Looking at it, the array_pop($this->params), inside the foreground of foreach, seems to be due to this sentence.

If the element of the '$this->params' array already being explored in the main loop statement is removed by an array_pop and then moved on to the next index, it appears to leave the loop door.

So the code that I modified is as below.

```
foreach(array_reverse($this->params) as &$param)
{
     $name = $param->getName();

     if(!$param->isOptional() && !isset($defaults[$name]) && !isset($params[$param->getName()]))
     {
         throw new \Exception('Missing "' . $name .'" parameter for "' . $this->getName() . '" route');
     }

     if(isset($defaults[$name]))
     {
         $param->value = $defaults[$param->getName()];
     }

     if(isset($params[$param->getName()]))
     {
         $param->value = $params[$param->getName()];
     }

     if(isset($defaults[$name]) || isset($params[$param->getName()]))
     {
         $path = str_replace($param->getSegment(), $param->value, $path);
     }
     else
     {
         $_path = explode('/', $path);
         array_pop($_path);
         $path = implode('/', $_path);
         //array_pop($this->params);
     }
}
```

Please review if this is applicable.

**Comment by andersonsalas** [comment]
Hi! :smiley:  Thanks for reporting it!

I've confirmed the bug and that `array_pop()` actually removes the Route parameter from the array, so the placeholder of the missing parameter is not iterated by the foreach and, in consequence, is not being removed from the generated route url.

**Comment by andersonsalas** [comment]
[Version 1.0.5](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v1.0.5) released
