### ISSUE TITLE
Passing arguments to middleware

### ISSUE THREAD

**Issue by ngekoding** [ingeniasoftware/luthier-ci#45]
Hi, thanks for this awesome library.

I just try to passing an argument to the Middleware, like for checking the user role.
The image below as the example from Laravel.

<img width="499" alt="Screenshot" src="https://user-images.githubusercontent.com/11625690/75310296-1d614f80-5886-11ea-8a00-c9a2d9e30487.png">

How can I do that?

**Comment by andersonsalas** [comment]
Hi @ngekoding!

Unfortunately there is no support for middleware parameters in `1.x` version of Luthier CI. This could be (and will be) an interesting addition for `2.0` version and I'll consider it.

**Comment by ngekoding** [comment]
Thank you, hopefully version 2.0 is coming soon.
