### ISSUE TITLE
How use session library in middleware

### ISSUE THREAD

**Issue by Indwr** [ingeniasoftware/luthier-ci#48]
Hello @andersonsalas

I create a middleware for check session but how I include the session library in middleware please help me

**Comment by andersonsalas** [comment]
Hi @Indwr, thanks for using Luthier CI.

The `ci()` helper returns the framework singleton, so you can use it to load libraries, helpers, etc.:

```php
<?php
# application/middleware/TestMiddleware.php

defined('BASEPATH') OR exit('No direct script access allowed');

class TestMiddleware implements Luthier\MiddlewareInterface
{
    /**
     * Middleware entry point
     *
     * @return void
     */
    public function run($args = [])
    {
        ci()->load->library('session');   
    }
}
```

The Luthier middleware is pretty simple in comparison to other frameworks such Laravel where you need to explicitly do something like `$next($request,$response)`. To prevent the controller get executed just use `exit()` or `die`:

```php
    public function run($args = [])
    {
        if ( !$condition ) {
             // Stops here. No controller is executed.
             die;
        }
        // Normal execution...
    }
```

However, there is a built-in user authentication system in Luthier Ci, you should take a look to the [documentation](https://luthier.ingenia.me/ci/en/help/documentation/1.0/authentication/simpleauth) for more information about SimpleAuth, it may help.

Cheers and happy codding!

**Comment by Indwr** [comment]
@andersonsalas  Thanks a lot..
