### ISSUE TITLE
Stop controller's funcions on using the middleware

### ISSUE THREAD

**Issue by mateusmcordeiro** [ingeniasoftware/luthier-ci#8]
Hi
First of all, I wanna thank you for my last issue.
Now, im facing a problem with my controllers functions, in other words, I'm using the middleware, but my controller is still using its functions. This is a problem, because I need the middleware stop that exec.

**Comment by andersonsalas** [comment]
Hi,

That's the normal behaviour of Luthier-CI; the controller will run after the middleware unless you stop the script execution explicitly. You can use the `die()` or `exit()` function inside your middleware to archieve that (`return` statement will not work)

```php
<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Test_middleware
{

    /**
     * Middleware entry point
     *
     * @return void
     */
    public function run()
    {
        /* YOUR CODE */
        exit; 
    }
}
```

Refer to [Middleware execution points](https://github.com/ingeniasoftware/luthier-ci#middleware-execution-points) topic for more information.

Cheers.

**Comment by Indwr** [comment]
Hello @andersonsalas  

I create a middleware for check session but how I include the session library in middleware please help me
