### ISSUE TITLE
404 on API routes

### ISSUE THREAD

**Issue by primapwd** [ingeniasoftware/luthier-ci#9]
Hi, I have this route
```
Route::get('api/test', function () {
	echo json_encode(['msg' => 'Hello World!']);
});
```

And whenever I call the route via ajax, it's always return 404 page not found.
Any idea? Or is it still experimental?

**Comment by andersonsalas** [comment]
Thanks for report it. I'll fix that in a moment

**Comment by andersonsalas** [comment]
[Version 0.2.0](https://github.com/ingeniasoftware/luthier-ci/releases/tag/v0.2.0) released :+1:

**Comment by primapwd** [comment]
Ah, thank you for fixing this. :+1:
